
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products =  [
  {
    _id: 1,
    title: " Nike Air Force 1 NDESTRUKT",
    price: "5000",
    category: "shoes",
    gender: "women",  
    img:"/assets/images/products/product_17.jpg",
    rating:3,
  },
  {
    _id: 2,
    title: "Nike Air Zoom Pegasus 37 A.I.R. Chaz Bear",
    price: "3000",
    category: "shoes",
    gender: "women",
    img:"/assets/images/products/product_2.jpg",
    rating:3.5,
  },  
  {
    _id: 3,
    title: "Zephyr top",
    price: "6000",
    category: "clothes",
    gender: "women",
    img:"/assets/images/products/cloth_1.jpg",
    rating:2,
  },
  {
    _id: 4,
    title: "Jordan Delta",
    price: "7000",
    category: "shoes",
    gender: "men",
    img:"/assets/images/products/product_3.jpg",
    rating:4,
  },
  {
    _id: 5,
    title: "Earrings",
    price: "2000",
    category: "jewellery",
    gender: "men",
    img:"/assets/images/products/jw_1.jpg",
    rating:4.5,
  },
  {
    _id: 6,
    title: "Kyrie 7 EP Sisterhood",
    price: "4000",
    category: "shoes",
    gender: "men",
    img:"/assets/images/products/product_4.jpg",
    rating:2.5,
  },
  {
    _id: 7,
    title: "Nike Air Zoom Pegasus 37 A.I.R. Chaz Bear",
    price: "11000",
    category: "shoes",
    gender: "kids",
    img:"/assets/images/products/product_5.jpg",
    rating:2,
  },
  {
    _id: 8,
    title: "Nike React Art3mis",
    price: "6500",
    category: "shoes",
    gender: "kids",
    img:"/assets/images/products/product_6.jpg",
    rating:2,
  },
  {
    _id: 9,
    title: "Zoom Freak 2",
    price: "1500",
    category: "shoes",
    gender: "kids",
    img:"/assets/images/products/product_7.jpg",
    rating:5,
  },
  {
    _id: 10,
    title: "Bracelet",
    price: "2030",
    category: "jewellery",
    gender: "men",
    img:"/assets/images/products/jw_2.jpg",
    rating:4.5,
  },
  {
    _id: 10,
    title: "Necklace",
    price: "8500",
    category: "jewellery",
    gender: "men",
    img:"/assets/images/products/jw_3.jpg",
    rating:4.5,
  },
  {
    _id: 11,
    title: "T-shirt ",
    price: "15000",
    category: "clothes",
    gender: "men",
    img:"/assets/images/products/cloth_2.jpg",
    rating:4.5,
  },
  {
    _id: 12,
    title: "Black T-shirt",
    price: "2900",
    category: "clothes",
    gender: "men",
    img:"/assets/images/products/cloth_3.jpg",
    rating:4.5,
  },
];
